name: hello-world
on: push
jobs:
   my-job:
     runs-on: ubuntu-latest
     steps:
       - name: my-step
         run: echo "Hello World! - 23BAD040"
       - name: collage
         run: echo "lab"
       - name:  workshop
         run: echo "attending workshop"
       - name: placement
         run: echo "job information"
       
         
